/* eslint-disable @next/next/no-img-element */
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>NFT Preview Card</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon-32x32.png"
        />
      </Head>
      <main className="bg-blue-main h-screen w-screen flex justify-center items-center px-6">
        <section className="w-[327px] h-[543px] bg-blue-card rounded-xl">
          <div className="p-6">
            <img
              src="/images/image-equilibrium.jpg"
              alt="equilibrium"
              className="rounded-lg"
            />

            <h3 className="text-2xl text-white mt-6 font-semibold">
              Equilibrium #3429
            </h3>
            <p className="text-soft-blue text-xl mt-3">
              Our Equilibrium collection promotes balance and calm.
            </p>
            <div className="flex justify-between items-center mt-3 border-b-[1px] border-blue-line pb-3">
              <div className="flex space-x-2 items-center">
                <img
                  src="/images/icon-ethereum.svg"
                  alt="Ethereum Icon"
                  className="h-[18px]"
                />
                <p className="text-md font-semibold text-cyan">0.041ETH</p>
              </div>
              <div className="flex space-x-2 items-center">
                <img
                  src="/images/icon-clock.svg"
                  alt="Clock Icon"
                  className="h-[18px]"
                />
                <p className="text-md font-medium text-soft-blue">
                  3 days left
                </p>
              </div>
            </div>
            <div className="flex gap-4 items-center mt-4">
              <img
                src="/images/image-avatar.png"
                alt="avatar"
                className="rounded-full h-[33px] border"
              />
              <p className="text-white"><span className="text-soft-blue">Creation of</span> Jules Wyvern</p>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
